name: Check GitHub Project Status and Notify Slack

on:
  schedule:
    - cron: "0 * * * *" # 毎時実行
  workflow_dispatch: # 手動実行も許可

jobs:
  check-project-status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Variables
        run: |
          export CURRENT_STATUS_FILE="project_status_current.json"
          export PREVIOUS_STATUS_FILE="project_status_previous.json"

      - name: Download Previous Status (Artifact)
        id: download_artifact
        uses: actions/download-artifact@v4
        with:
          name: previous-status
          path: .
        continue-on-error: true

      - name: Get GitHub Project Status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Install required tools
          sudo apt-get update && sudo apt-get install -y jq

          # GitHub GraphQL API Endpoint
          GRAPHQL_API="https://api.github.com/graphql"

          # Query to get current status
          QUERY='{ "query": "query { node(id: \"YOUR_PROJECT_ID\") { ... on ProjectV2 { items(first: 50) { nodes { id content { ... on Issue { title state } } } } } } }" }'

          # Fetch current status and save to file
          curl -s -H "Authorization: bearer $GITHUB_TOKEN" -X POST -d "$QUERY" $GRAPHQL_API \
            | jq > "$CURRENT_STATUS_FILE"

      - name: Compare Status
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          # Compare with previous status (if available)
          if [ -f "$PREVIOUS_STATUS_FILE" ]; then
            DIFF=$(diff "$PREVIOUS_STATUS_FILE" "$CURRENT_STATUS_FILE" || true)
          else
            DIFF="No previous status available for comparison."
          fi

          echo "Change detected! Sending Slack notification..."
          MESSAGE="GitHub Project Status Changed:\n\`\`\`${DIFF}\`\`\`"
          echo "$MESSAGE"

          # Check if SLACK_WEBHOOK is set
          if [[ -z "$SLACK_WEBHOOK" ]]; then
            echo "SLACK_WEBHOOK is not set. Skipping Slack notification."
          else
            # If differences exist, send Slack notification
            if [[ "$DIFF" != "" ]]; then
              curl -X POST -H 'Content-type: application/json' \
                --data "$(jq -n --arg text "$MESSAGE" '{text: $text}')" \
                $SLACK_WEBHOOK
            else
              echo "No changes detected."
            fi
          fi

      - name: Upload Current Status (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: previous-status
          path: project_status_current.json
          overwrite: true